<?php

namespace AppBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findTrainerCities()
    {
        return $this->createQueryBuilder('u')

            ->getQuery()->getArrayResult();
    }
}
