<?php

namespace AppBundle\Repository;

/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFeedbackByTrainer($user)
    {
        return $this->createQueryBuilder('f')
            ->leftJoin('f.fos_user_author', 'u')
            ->addSelect('u')
            ->where('f.fos_user_object = :object_id')
            ->setParameter(':object_id', $user)->getQuery()->getArrayResult();
    }
    public function findFeedbackByClientAndTrainer($user) {
        return $this->createQueryBuilder('f')
            ->leftJoin('f.fos_user_object', 'u')
            ->addSelect('u')
            ->where('f.fos_user_author = :author')
            ->setParameter(':author', $user)->getQuery()->getArrayResult();
    }
    public function findFeedbackByClient($user)
    {
        return $this->createQueryBuilder('f')
            ->leftJoin('f.fos_user_author', 'u')
            ->addSelect('u')
            ->where('f.fos_user_author = :object_id')
            ->setParameter(':object_id', $user)->getQuery()->getArrayResult();
    }
}
