<?php

namespace AppBundle\Repository;

/**
 * ReservationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findIfRegistered(\AppBundle\Entity\User $user, \AppBundle\Entity\TrainingTime $trainingTime)
    {
        try {
            return $this->createQueryBuilder('r')
                ->where('r.fosUser = :user AND r.trainingTime = :training')
                ->setParameters(['user' => $user, 'training' => $trainingTime])
                ->getQuery()->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return false;
        }
    }
}
