<?php

namespace AppBundle\Repository;

/**
 * TrainingTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingTimeRepository extends \Doctrine\ORM\EntityRepository
{
}
