<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingRepository extends EntityRepository
{
    /**
    * Find trainings by user in trainer page
    * @param User $user
    * @return array
    */
    public function findByUser($user)
    {
        return $this->createQueryBuilder('t')
            ->leftJoin('t.category', 'ca')
            ->addSelect('ca')
            ->leftJoin('t.city', 'ci')
            ->addSelect('ci')
            ->where('t.fosUser = :user')
            ->setParameter(':user', $user)->getQuery()->getArrayResult();
    }
    /**
    * Find all categories that exist in trainings
    * @return array
    */
    public function findCategories()
    {
        return $this->createQueryBuilder('t')
            ->leftJoin('t.category', 'ca')
            ->addSelect('ca')
            ->select('ca.title')
            ->getQuery()->getArrayResult();
    }
    /**
    * Find all cities that exist in trainings
    * @return array
    */
    public function findCities()
    {
        return $this->createQueryBuilder('t')
            ->leftJoin('t.city', 'ci')
            ->addSelect('ci')
            ->select('ci.title')
            ->getQuery()->getArrayResult();
    }
    /**
    * Find training and trainings times by id
    * @return array
    */
    public function findWithTimes($training)
    {
        return $this->createQueryBuilder('training')
            ->leftJoin('training.trainingTime', 'training_time')
            ->addSelect('training_time')
            ->where('training.id = :training')
            ->setParameter(':training', $training)->getQuery()->getSingleResult();
    }
}
