<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * TrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingRepository extends EntityRepository
{
    public function findByUser($user)
    {
        return $this->createQueryBuilder('t')->where('t.fos_user = :trainer')
                ->setParameter(':trainer', $user)->getQuery()->getArrayResult();
    }
}
