<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findByRoles($role) {

        return $this->createQueryBuilder('u')->where('u.roles LIKE :role')
            ->setParameter(':role', '%"'.$role.'"%')->getQuery()->getArrayResult();

    }
}
